# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
